baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown


# Dependencies
highlighter:         rouge

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Thought Box
tagline:          'A random walk'
description:      'Life on the Pareto Frontier'
# url:              http://blog.jnbrymn.com
# baseurl:          / #prolly can't use this

# author:
#   name:           'John Berryman'
#   url:            https://twitter.com/JnBrymn

paginate:         5

# # Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/JnBrymn/

# exclude:
#   - _drafts/hidden